#include "fsl_gpio.h"
#include "pin_mux.h"

void disable_all_leds() {
	GPIO_PinWrite(BOARD_INITPINS_LED_RED_F_L_GPIO, BOARD_INITPINS_LED_RED_F_L_PIN, 1);
	GPIO_PinWrite(BOARD_INITPINS_LED_RED_F_R_GPIO, BOARD_INITPINS_LED_RED_F_R_PIN, 1);
	GPIO_PinWrite(BOARD_INITPINS_LED_RED_R_L_GPIO, BOARD_INITPINS_LED_RED_R_L_PIN, 1);
	GPIO_PinWrite(BOARD_INITPINS_LED_RED_R_R_GPIO, BOARD_INITPINS_LED_RED_R_R_PIN, 1);
	GPIO_PinWrite(BOARD_INITPINS_LED_GREEN_F_L_GPIO, BOARD_INITPINS_LED_GREEN_F_L_PIN, 1);
	GPIO_PinWrite(BOARD_INITPINS_LED_GREEN_F_R_GPIO, BOARD_INITPINS_LED_GREEN_F_R_PIN, 1);
	GPIO_PinWrite(BOARD_INITPINS_LED_BLUE_F_L_GPIO, BOARD_INITPINS_LED_BLUE_F_L_PIN, 1);
	GPIO_PinWrite(BOARD_INITPINS_LED_BLUE_F_R_GPIO, BOARD_INITPINS_LED_BLUE_F_R_PIN, 1);
}
